<div id = "Main">
			
			<?php
			include("sidebar/sidebar.php");
			?>
			<div class = "Maincontent">
				<?php
				if(isset($_GET['quanly']))
				{
					$tam=$_GET['quanly'];
				}
				else
				{
					$tam='';	
				}	
				if ($tam=='danhmucsanpham')
				{
					include("Main/danhmuc.php");
				}
				elseif($tam=='giohang')
				{
					include("Main/giohang.php");
				}
				elseif($tam=='danhmucbaiviet')
				{
					include("Main/danhmucbaiviet.php");
				}
				elseif($tam=='baiviet')
				{
					include("Main/baiviet.php");
				}
				elseif($tam=='dangky')
				{
					include("Main/dangky.php");
				}	
				elseif($tam=='thaydoimatkhau')
				{
					include("Main/thaydoimatkhau.php");
				}
				elseif($tam=='dangnhap')
				{
					include("Main/dangnhap.php");
				}
				elseif($tam=='thanhtoan')
				{
					include("Main/thanhtoan.php");
				}
				elseif($tam=='tintuc')
				{
					include("Main/tintuc.php");
				}
				elseif($tam=='camon')
				{
					include("Main/camon.php");
				}
				elseif($tam=='timkiem')
				{
					include("Main/timkiem.php");
				}
				elseif($tam=='lienhe')
				{
					include("Main/lienhe.php");
				}
				elseif($tam=='danhsachsp')
				{
					include("Main/danhsachsp.php");
				}
				else
				{
					include("Main/maincontent.php");
				}	
				?>
			</div>

		</div>